<script type="text/javascript">

  // var _gaq = _gaq || [];
  // _gaq.push(['_setAccount', 'UA-7370043-1']);
  // _gaq.push(['_trackPageview']);

  // (function() {
  //   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  //   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  //   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  // })();

</script>
<!-- End page specific content (leg_Col4of4-First)-->
</div>
<!--General Information and Quick Links panels -->
<div class="leg_Col1of4-Last leg_HiddenMobile">  <!-- begin column -->        

</div>
<!-- End page specific content (leg_PageContent-First)-->
</div>
<!-- begin: footer section -->
<div class="leg_PageFooter" id="leg_PageFooter" tabindex="0" >
    <div class="leg_HiddenNonmobile">
        <h2><a class="leg_ViewFull" href="#">View full site</a></h2>
    </div>

     <div class="leg_Col1of4-First">
        <h2><a href="http://www.leg.state.mn.us/leg/faq/faqtoc.aspx?subject=1">About the Legislature</a></h2>
        <ul>
            <li><a href="http://www.leg.state.mn.us/leg/faq/faqtoc.aspx">FAQ</a></li>
            <li><a href="http://www.leg.state.mn.us/leg/howbill.aspx">Guide to the Legislative Process</a></li>
            <li><a href="http://www.leg.state.mn.us/lrl/histleg/">Historical Information</a></li>            
            <li><a href="http://www.leg.state.mn.us/leg/jobs.aspx">Employment/Internships</a></li>
            <li><a href="http://www.leg.state.mn.us/leg/faq/faqtoc.aspx?subject=14">Visiting the Capitol</a></li>
            <li><a href="http://www.gis.leg.mn/html/maps.html">Maps</a></li>
            <li><a href="http://www.gis.leg.mn/OpenLayers/districts/">Who Represents Me?</a></li>
            <li><a href="http://www.leg.state.mn.us/leg/accessibility.aspx">Accessibility</a></li>
        </ul>
    </div>

    <div class="leg_Col2of4">
        <h2 class="leg_Title"><a href="http://www.leg.state.mn.us/leg/legdir.aspx">Contact Us</a></h2>
        <div class="leg_Col2of4-First">
            <ul>
                <li><h2>For all comments concerning legislation or issues:</h2></li>
                <li><a href="http://www.house.leg.state.mn.us/members/hmem.asp">Contact your House Member</a></li>
                <li><a href="http://www.senate.leg.state.mn.us/members/index.php">Contact your Senator</a></li>
            </ul>
        </div>
        <div class="leg_Col2of4-Last">
            <ul>
                <li><h2>For general information:</h2></li>
                <li>Contact a legislative librarian:</li>
                <li>651-296-8338 or <a href="http://www.leg.state.mn.us/leg/comments.aspx">email</a>.</li>
            </ul>
                <ul>
                <li><a href="http://www.leg.state.mn.us/leg/faq/faqtoc.aspx?id=98">View services for users with a hearing or speech disability</a></li>
            </ul>
      
            <ul>
                <li><a href="http://www.leg.state.mn.us/leg/comments.aspx">Submit website comments</a></li>            
            </ul>
        </div>
    </div>
    
    <div class="leg_Col1of4-Last leg_AlignR">
        <h2><a href="http://www.leg.state.mn.us/leg/elists.aspx">Get Connected</a></h2>
        <ul>
            <li><a href="http://www.house.leg.state.mn.us/leg/billsublogin.asp">MyBills</a></li>
            <li><a href="http://www.leg.state.mn.us/leg/elists.aspx">E-mail Updates &amp; RSS Feeds</a></li>
            <li><a href="http://www.house.mn/hinfo/news.asp">House News</a></li>
            <li><a href="http://www.senate.leg.state.mn.us/media/">Senate News</a></li>
            <li><a href="http://www.leg.state.mn.us/leg/legdir.aspx">Phone Numbers</a></li>
        </ul>           
    </div>
</div>

<div class="leg_PageFooterAddr">
    <p>LCC-GIS Office &nbsp;&nbsp;&middot;&nbsp;&nbsp;55 State Office Building, St. Paul, MN 55155 &nbsp;&nbsp;&middot;&nbsp;&nbsp;gis@gis.leg.mn </p>
</div>
<!-- end: footer section -->

</div>
<!-- end: leg_shell -->

<!--[if lt IE 8 ]> </div> <![endif]-->
</body>
</html>