
    <title>Minnesota Legislature - Geographic Information Services</title>
    <!--Begin Copy Section-->
    <!-- I just change the meta content here rather than js later -->
    <meta charset="UTF-8" />  <!-- for html5 -->
    <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />  <!-- for iPad tablet -->
    <meta name="Description" content="Minnesota Legislature | LCC-GIS" />
    <meta name="Keywords" content="state government, legislature, districts, who represents me" />
    <META name="DC.Language" content="English">
    <meta  HTTP-EQUIV="Cache-Control" content="public">
    <link rel="stylesheet" type="text/css" href="http://www.gis.leg.mn/css/aux_css_20.css" />
    <link rel="stylesheet" type="text/css" href="http://www.gis.leg.mn/css/leg_css_20.css" />
       


<link rel="stylesheet" type="text/css" media="print" href="http://www.gis.leg.mn/css/leg_cssprint_20.css" />
</head>

<body>
<!-- Google Tag Manager -->
<script>
  dataLayer = [];
</script>
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-WXZXH4"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WXZXH4');</script>
<!-- End Google Tag Manager -->
<!-- End Google Tag Manager -->
<!--[if lt IE 8 ]> <div class="leg_IEOld"> <![endif]-->  <!-- wrapper for <=IE7 checks -->

<!-- start: mobile-specifc top header -->
<div class="leg_mobile_TopHeader"> 
    <div class="leg_mobile_MainTitle">
        <a href="http://www.gis.leg.mn">LCC-GIS Office</a>
    </div>
    <div class="leg_mobile_MainTitle leg_mobile_Leglink">
	<a href="http://www.leg.state.mn.us/">MN Legislature</a>
    </div>
</div>
<!-- end: mobile-specifc top header -->

<!-- start: shell for all page sections -->
<div class="leg_Shell" id="leg_shell">   

<!-- start: header section - common navigvation links, banner, office/dept contextual nav -->
<div class="leg_PageHeader">    

    <!-- accessibility menu for easy navigation using screen readers -->
    <div class="leg_Offscreen">
        <h2>Accessibility menu</h2>
        <ul>   
            <li><h3><a href="#leg_PageContent" accesskey="c">Skip to main content </h3></a></li>
            <li><h3><a href="#leg_OfficeNav" accesskey="n">Skip to LCC-GIS Office navigation</h3></a></li>
            <li><h3><a href="#leg_PageFooter" accesskey="f">Skip to footer</h3></a></li>
        </ul>
    </div>
    <!-- end: accessibility -->
    <!-- start: preliminary navigation -->
    <!-- start: preliminary navigation - begin paste -->
    <div class="leg_FirstNav">
        <ul  class="leg_ul_FirstNav">
            <li><a class="leg_IconLeg" href="http://www.leg.state.mn.us/">MN Legislature</a></li>
            <li><a class="leg_IconConn" href="http://www.leg.state.mn.us/leg/elists.aspx">Get Connected</a></li>                
            <li><a class="leg_IconAbout" href="http://www.leg.state.mn.us/leg/faq/faqtoc.aspx?subject=1">About the Legislature</a></li>
            <li><a class="leg_IconMobile"  href="#" >Mobile Site</a></li>
        </ul>

        <div class="leg_FirstNavR">
            	<form id="sitesearchform" name="sitesearchform" action="http://www.leg.state.mn.us/search.aspx" method="get">
                <label for="leg_mainSearch" class="leg_Offscreen">Search the MN Legislature</label>
                <input class="leg_DefaultText" name="mainsearch" type="text" value="Search the MN Legislature" maxlength="200" style="width: 185px;" />
                <input id="leg_mainSearch" class="leg_ButtonSearch" value="Submit" type="submit" />
		    </form>
        </div>
    </div>
    <!-- end: preliminary navigation -->

    <!-- start: mobile-specifc main nav heading -->
    <div class="leg_mobile_NavHeader" id="leg_mobile_LegNavHeader">             
        <h2>Menu</h2>
    </div>
    <!-- end: mobile-specifc main nav heading -->

    <!-- start: main legislative nav -->
    <div class="leg_LegNav" id="leg_LegNav">
	    <ul>
            <li class="leg_NavItem">
                <a class="leg_LegNavTop" href="http://www.house.leg.state.mn.us/" accesskey="h">House</a>    
                <a class="leg_mobile_Accordion">&nbsp;</a>
                
                <div class="leg_LegNavCore" id="leg_nav_house">
                    <h2>Minnesota House of Representatives</h2>
                    <ul>
                        <li><h3>House Members and Staff</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/members/hmem.asp">House Members</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/members/houseleaders.asp">Leadership</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/staff.asp">Staff</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/has/employment.asp">Employment</a></li>
                    </ul>
                    <ul>
                        <li><h3>Committees</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/comm/commemlist.asp">Committee List</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/leginfo/comroster.pdf">Committee Roster</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/scheduleall.asp">Upcoming Meetings</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/11comgrid.pdf">Standing Committee Schedule</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/comm/commminutes.asp">Minutes</a></li>
                        <li><a href="http://www.leg.state.mn.us/leg/deadlines.aspx">Committee Deadlines</a></li>                   
                    </ul>
                    <ul>
                        <li><h3>Offices</h3></li>                        
                        <li><a href="http://www.house.leg.state.mn.us/cco/cco.asp">Chief Clerk</a></li>
    		            <li><a href="http://www.house.leg.state.mn.us/fiscal/fahome.asp">Fiscal Analysis</a></li>	    		
	    	            <li><a href="http://www.house.leg.state.mn.us/hrd/hrd.aspx">House Research</a></li>
	    	            <li><a href="http://www.house.leg.state.mn.us/hinfo/hinfo.asp">Public Information</a></li> 
                        <li><a href="http://www.house.leg.state.mn.us/sergeant/sergeant.asp">Sergeant-at-Arms</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/caucuses.asp">Caucuses - DFL/GOP</a></li>
                    </ul>         
                    <ul>
                        <li><h3>Other Information</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/cco/journals/journl.asp">House Journal</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/cco/rules/permrule/permrule.asp">House Rules</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/cco/rules/jtrule/jtrule.asp">Joint Rules</a></li>
    		            <li><a href="http://www.house.leg.state.mn.us/sergeant/education.asp">Educational Programs</a></li>
                    </ul>
                </div>
            </li>

            <li class="leg_NavItem">
                <a class="leg_LegNavTop" href="http://www.senate.mn/" accesskey="s">Senate</a>
                <a class="leg_mobile_Accordion">&nbsp;</a>          

                <div class="leg_LegNavCore" id="leg_nav_senate">
                    <h2>Minnesota Senate</h2>
                    <ul>
                        <li><h3>Senators and Staff</h3></li>
                        <li><a href="http://www.senate.mn/members/index.php?ls=#header">Senators</a></li>
                        <li><a href="http://www.senate.mn/members/index.php?ls=#leader">Leadership</a></li>
                        <li><a href="http://www.senate.mn/employees/employee_list.php?ls=">Staff</a></li>
                        <li><a href="http://www.senate.mn/jobs/index.php?office_id=1005&amp;div_id=1020#header">Employment</a></li>
                    </ul>
                    <ul>
                        <li><h3>Committees</h3></li>
                        <li><a href="http://www.senate.mn/committees">Committee List</a></li>
                        <li><a href="http://www.senate.leg.state.mn.us/committees/display_pdf_cmte_roster.php">Committee Roster</a></li>                        
                        <li><a href="http://www.senate.mn/schedule/schedule.php?ls=&amp;cmte_id=&amp;cmte_type=&amp;type=upcoming">Upcoming Meetings</a></li>
                        <li><a href="http://www.senate.mn/committees/cmte_meeting_schedule.php?ls=">Standing Committee Schedule</a></li>
                        <li><a href="http://www.leg.state.mn.us/leg/deadlines.aspx">Committee Deadlines</a></li>
                    </ul>
                    <ul>
                        <li><h3>Offices</h3></li>                        
                        <li><a href="http://www.senate.mn/departments/office_bio.php?office_id=1005&amp;ls=">Secretary of the Senate</a></li>
	    		        <li><a href="http://www.senate.mn/departments/office_bio.php?office_id=1007&amp;ls=">Senate Counsel, Research &amp; Fiscal Analysis</a></li>             	        
                        <li><a href="http://www.senate.leg.state.mn.us/caucus/index.php?ls=#header">Caucuses - DFL/GOP</a></li>
                    </ul>
                    <ul>
                        <li><h3>Other Information</h3></li>
                        <li><a href="http://www.senate.leg.state.mn.us/journals/index.php#current">Senate Journal</a></li>
                        <li><a href="http://www.senate.mn/rules/index.php?ls=#rulesofthesenate">Senate Rules</a></li>
    			        <li><a href="http://www.senate.mn/rules/index.php#jointrules">Joint Rules</a></li>
                        <li><a href="http://www.senate.leg.state.mn.us/departments/secretary/info/interns/index.php#header">Educational Programs</a></li>
                    </ul>

                </div>
            </li>

            <li class="leg_NavItem">               
                <a class="leg_LegNavTop" href="http://www.commissions.leg.state.mn.us/depts.htm" accesskey="j">Joint</a>
                <a class="leg_mobile_Accordion">&nbsp;</a>

                <div class="leg_LegNavCore" id="leg_nav_joint">
                    <h2>Joint Departments, Offices, and Commissions</h2>
                    <ul class="leg_NavCol2of4">
                        <li><h3>Joint Legislative Offices</h3></li>
                        <li><a href="https://www.revisor.mn.gov/">Revisor of Statutes</a></li>
                        <li><a href="http://www.leg.state.mn.us/lrl/lrl.aspx">Legislative Reference Library</a></li> 
                        <li><a href="http://www.auditor.leg.state.mn.us/">Office of the Legislative Auditor</a></li>
                    </ul>
                    <ul class="leg_NavCol2of4">
                        <li><h3>Commissions</h3></li>                                               
                        <li><a href="http://www.lcc.leg.mn/">Legislative Coordinating Commission (LCC)</a></li> 
                        <li><a href="http://www.lccmr.leg.mn/">Legislative-Citizen Commission on MN Resources (LCCMR)</a></li>
                        <li><a href="http://www.lcpr.leg.mn/">Legislative Commission on Pensions &amp; Retirement (LCPR)</a></li>                    
                        <li><a href="http://www.lsohc.leg.mn/">Lessard-Sams Outdoor Heritage Council</a></li>
                        <li><a href="http://www.legacy.leg.mn/">Legacy Amendment</a></li>      
                        <li><a href="http://www.commissions.leg.state.mn.us/">More...</a></li>
                    </ul>
                </div>
            </li>      
    
            <li class="leg_NavItem">
                <a class="leg_LegNavTop" href="http://www.leg.state.mn.us/leg/sched.aspx" accesskey="e">Schedules</a>
                <a class="leg_mobile_Accordion">&nbsp;</a>

                <div class="leg_LegNavCore" id="leg_nav_schedules">
                    <h2>Schedules, Calendars, and Legislative Business</h2>                    
                    <ul>  
                        <li><h3>House</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/hinfosched.asp">House Schedules</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/cco/orders/orders.htm">Order of Business</a></li> 
                        <li><a href="http://www.house.leg.state.mn.us/cco/calendar.asp">Calendar for the Day</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/cco/calendarsup.asp">Supplemental Calendar for the Day</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/cco/fiscal.asp">Fiscal Calendar</a></li> 
                    </ul>
                    <ul>
                        <li><h3>Senate</h3></li>
                        <li><a href="http://www.senate.leg.state.mn.us/schedule/schedule.php?ls=">Senate Schedules</a></li>
                        <li><a href="http://www.senate.mn/orders/index.php#header">Order of Business</a></li>
                        <li><a href="http://www.senate.mn/orders/calendar.html">Senate Calendar</a></li>
                        <li><a href="http://www.senate.mn/orders/go.html">General Orders of the Day</a></li>                        
                    </ul>
                    <ul>
                        <li><h3>Joint</h3></li>
                        <li><a href="http://www.leg.state.mn.us/calendarday.aspx">Combined Upcoming Meetings</a></li>                        
                        <li><a href="http://www.house.leg.state.mn.us/htv/htv.asp">Broadcast TV Schedule</a></li>
                        <li><a href="http://www.leg.state.mn.us/leg/deadlines.aspx">Committee Deadlines</a></li>
                    </ul>
                </div>
            </li>            
        
            <li class="leg_NavItem">
                <a class="leg_LegNavTop" href="http://www.leg.state.mn.us/leg/legislators.aspx" accesskey="r">Legislators</a>
                <a class="leg_mobile_Accordion">&nbsp;</a>

                <div class="leg_LegNavCore" id="leg_nav_legislators">
                    <h2>Legislators</h2>      
                     <ul>
                        <li><h3>House</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/members/housemembers.asp">House Members</a></li>   
                        <li><a href="http://www.house.leg.state.mn.us/members/pronunciation.asp">Pronunciation Guide</a></li>  
                        <li><a href="http://www.house.leg.state.mn.us/members/houseleaders.asp">Leadership</a></li> 
                        <li><a href="http://www.house.leg.state.mn.us/members/meminfo.xls">Address Spreadsheet</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/caucuses.asp">Caucuses - DFL/GOP</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/votes/memvotes.asp">Floor Votes by Member</a></li>
                    </ul>
                    <ul>
                        <li><h3>Senate</h3></li>
                        <li><a href="http://www.senate.mn/members/index.php?ls=#header">Senators</a></li>
                        <li><a href="http://www.senate.mn/members/member_pronounce.php?ls=#header">Pronunciation Guide</a></li> 
                        <li><a href="http://www.senate.mn/members/index.php?ls=#leader">Leadership</a></li>
                        <li><a href="http://www.senate.mn/members/member_labels_page.php?ls=">Address Labels</a></li>
                        <li><a href="http://www.senate.leg.state.mn.us/caucus/index.php?ls=#header">Caucuses - DFL/GOP</a></li>
                    </ul>
                    <ul>
                        <li><h3>Joint</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/leginfo/memroster.pdf">Legislators Roster</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/leginfo/elecdir10.pdf">Election Directory</a></li>                        
                        <li><a href="http://www.leg.state.mn.us/legdb/">Legislators Past &amp; Present</a></li>
                        <li><a href="http://www.leg.state.mn.us/leg/districtfinder.aspx">Who Represents Me?</a></li>
                    </ul>
                </div>
            </li>

            <li class="leg_NavItem">
                <a class="leg_LegNavTop" href="http://www.leg.state.mn.us/leg/committees.aspx" accesskey="t">Committees</a>
                <a class="leg_mobile_Accordion">&nbsp;</a>

                <div class="leg_LegNavCore" id="leg_nav_committees">
                    <h2>Legislative Committees</h2>       
                     <ul>
                        <li><h3>House</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/comm/commemlist.asp">Committee List</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/leginfo/comroster.pdf">Committee Roster</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/scheduleall.asp">Upcoming Meetings</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/11comgrid.pdf">Standing Committee Schedule</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/comm/commminutes.asp">Minutes</a></li>
                    </ul>
                    <ul>
                        <li><h3>Senate</h3></li>
                        <li><a href="http://www.senate.mn/committees">Committee List</a></li>
                        <li><a href="http://www.senate.leg.state.mn.us/committees/display_pdf_cmte_roster.php">Committee Roster</a></li>                        
                        <li><a href="http://www.senate.mn/schedule/schedule.php?ls=&amp;cmte_id=&amp;cmte_type=&amp;type=upcoming">Upcoming Meetings</a></li>
                        <li><a href="http://www.senate.mn/committees/cmte_meeting_schedule.php?ls=">Standing Committee Schedule</a></li>
                    </ul>
                    <ul>
                        <li><h3>Joint</h3></li>
                        <li><a href="http://www.commissions.leg.state.mn.us/">Joint Committees &amp; Task Forces</a></li>
                        <li><a href="http://www.leg.state.mn.us/leg/deadlines.aspx">Committee Deadlines</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/bills/confcommactivity.asp">Bills In Conference Committtee</a></li>
                        <li><a href="https://www.revisor.mn.gov/bin/sbs.php">Side by Side Comparisons</a></li>                        
                    </ul>
                </div>

            </li>

            <li class="leg_NavItem">
                <a class="leg_LegNavTop" href="http://www.leg.state.mn.us/leg/legis.aspx" accesskey="b">Bills</a>
                <a class="leg_mobile_Accordion">&nbsp;</a>

                <div class="leg_LegNavCore" id="leg_nav_bills">
                    <h2>Bills</h2>       
                    <ul>
                        <li><h3>House</h3></li>
                        <li>
                            <form id="hfsearchform" name="billform" action="http://www.house.leg.state.mn.us/bills/billnum.asp" method="get">
                                <input class="leg_DefaultText" id="Billnumber" name="Billnumber" value="Search HF" type="text" style="width: 100px;" maxlength="7" />                                
                                <input class="leg_ButtonSearch" value="Submit" type="submit" />
                            </form>
                        </li>  
                        <li><a href="http://www.house.leg.state.mn.us/cco/introductions.asp">Bill Introductions</a></li> 
                        <li>Summaries: <a href="http://www.house.leg.state.mn.us/hrd/billsum.aspx">Bill</a> | <a href="http://www.house.leg.state.mn.us/hrd/actsum.aspx">Act</a></li> 
                        <li><a href="http://www.house.leg.state.mn.us/fiscal/tracking.asp">Fiscal Tracking Sheets</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/bills/hotlistarchives.asp">Hot List</a></li>                        
                        <li><a href="https://www.revisor.mn.gov/bills/status_search.php?body=House">Bill Search &amp; Status (House)</a></li>
                    </ul>
                    <ul>
                        <li><h3>Senate</h3></li>
                        <li>
                            <form id="sfsearchform" name="billform" action="http://www.senate.leg.state.mn.us/bills/billinf.php" method="get">
                                <input class="leg_DefaultText" name="billnum" value="Search SF" type="text" style="width: 100px;" maxlength="7" />
                                <input class="leg_ButtonSearch" value="Submit" type="submit" />
                            </form>
                        </li>
                        <li><a href="http://www.senate.mn/orders/intros/index.php#header">Bill Introductions</a></li> 
                        <li>Summaries: <a href="http://www.senate.leg.state.mn.us/departments/scr/billsumm/index.php?summary_type=bill#header">Bill</a> | 
                            <a href="http://www.senate.leg.state.mn.us/departments/scr/billsumm/index.php?ls=&amp;sumtype=act#header">Act</a></li> 
                        <li><a href="http://www.senate.leg.state.mn.us/departments/fiscalpol/tracking/index.php?ls=#header">Fiscal Tracking Sheets</a></li>
                        <li><a href="http://www.senate.mn/departments/secretary/info/publications/popularbills.pdf">Hot List</a></li>
                        <li><a href="https://www.revisor.mn.gov/bills/status_search.php?body=Senate">Bill Search &amp; Status (Senate)</a></li>
                    </ul>
                    <ul>
                        <li><h3>Joint</h3></li>
                        <li><a href="http://www.leg.state.mn.us/leg/legis.aspx">Bill Search &amp; Status</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/leg/billsublogin.asp">MyBills</a></li>
                        <li><a href="https://www.revisor.mn.gov/bin/sbs.php">Side by Side Comparisons</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/bills/confcommactivity.asp">Bills In Conference Committtee</a></li>
                        <li><a href="http://www.leg.state.mn.us/lrl/vetoes/vetodetails.aspx">Vetoes</a></li>
                        <li><a href="https://www.revisor.mn.gov/laws/current/">Current Session Laws</a></li>
                    </ul> 
                </div>
            </li>
    
            <li class="leg_NavItem">
                <a class="leg_LegNavTop" href="https://www.revisor.mn.gov/pubs/" accesskey="l">Law</a>
                <a class="leg_mobile_Accordion">&nbsp;</a>

                <div class="leg_LegNavCore" id="leg_nav_mnlaw">
                    <h2>Statutes, Laws, and Rules</h2>
                    <ul>
                        <li><h3>Statutes</h3></li>
                        <li>
                            <form id="statutesearchform" name="statutesearchform" action="https://www.revisor.mn.gov/statutes/" method="get">
                                <input class="leg_DefaultText" name="id" value="Lookup Statute" type="text" style="width: 100px;" maxlength="10" />
                                <input class="leg_ButtonSearch" value="Submit" type="submit" />
                            </form>
                        </li>
                        <li><a href="https://www.revisor.mn.gov/search/?search=all&amp;stat=1&amp;laws=1&amp;rule=1&amp;court=1">Keyword Search</a></li>
                        <li><a href="https://www.revisor.mn.gov/statutes/">Current Statutes</a></li>
                        <li><a href="https://www.revisor.mn.gov/statutes/?view=index">Statutes by Topic (Index)</a></li>
                        <li><a href="https://www.revisor.mn.gov/statutes/?view=archive">Statutes Archive</a></li>
                    </ul>        
                    <ul>
                        <li><h3>Session Laws</h3></li>
                        <li><a href="https://www.revisor.mn.gov/search/?search=all&amp;stat=0&amp;laws=1&amp;rule=0&amp;court=0">Keyword Search</a></li>
                        <li><a href="https://www.revisor.mn.gov/laws/current/">Current Session Laws</a></li>  
                        <li><a href="https://www.revisor.mn.gov/topics/?type=laws">Session Laws by Topic (Index)</a></li>  
                        <li><a href="https://www.revisor.mn.gov/laws/">Session Laws Archive</a></li>                          
                        <li><a href="https://www.revisor.mn.gov/laws/law_action.php">Session Laws Changed (Table 1)</a></li>  
                        <li><a href="https://www.revisor.mn.gov/statutes/statute_action.php?full=0">Statutes Changed (Table 2)</a></li>                           
                    </ul>        
                    <ul>
                        <li><h3>Administrative Rules</h3></li>
                        <li><a href="https://www.revisor.mn.gov/search/?search=all&amp;stat=0&amp;laws=0&amp;rule=1&amp;court=0">Keyword Search</a></li>
                        <li><a href="https://www.revisor.mn.gov/rules/">Current Rules</a></li> 
                        <li><a href="https://www.revisor.mn.gov/topics/?type=rule">Rules by Topic (Index)</a></li> 
                        <li><a href="https://www.revisor.mn.gov/rules/?view=archive">Rules Archive</a></li> 
                        <li><a href="https://www.revisor.mn.gov/rules/rule_search.php">Minnesota Rule Status</a></li>  
                        <li><a href="https://www.revisor.mn.gov/state_register/">State Register</a></li>                                             
                    </ul>
                    <ul>
                        <li><h3>Other Legal Materials</h3></li>
                        <li><a href="https://www.revisor.mn.gov/constitution/">Minnesota Constitution</a></li>
                        <li><a href="http://www.leg.state.mn.us/lrl/mngov/constitutionalamendments.aspx">State Constitutional Amendments</a></li>
                        <li><a href="https://www.revisor.mn.gov/court_rules/">Court Rules</a></li>
                    </ul>            
                </div>
            </li>
    
            <li class="leg_NavItem">
                <a class="leg_LegNavTop" href="http://www.leg.state.mn.us/leg/multimedia.aspx" accesskey="m">Multimedia</a>
                <a class="leg_mobile_Accordion">&nbsp;</a>

                <div class="leg_LegNavCore" id="leg_nav_multimedia">
                    <h2>Multimedia — Audio, Video, Broadcast TV, News, &amp; Photos</h2>      
                    <ul>             
                        <li><h3>House</h3></li>
                        
                            <li><a href="http://www.house.leg.state.mn.us/htv/mnhouse.asx">Live Video</a></li> 
                        <li><a href="http://www.house.leg.state.mn.us/htv/schedule.asp">Webcast Schedule</a></li>                        
                        <li><a href="http://www.house.leg.state.mn.us/audio/default.asp">Audio &amp; Video Archives</a></li> 
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/sdaily.asp">Session Daily</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/images.asp">Photos</a></li>
                    </ul>
                    <ul>
                        <li><h3>Senate</h3></li>
                        <li ><a href="http://www.senate.leg.state.mn.us/senate_video.php?ls=&media_type=flv" class="leg_HiddenMobile">Live Video</a> 
                            <a href="http://stream1.video.state.mn.us:8080/m3ugen/broadcast/Senatemobile.3gp" class="leg_HiddenNonmobile">Live Video</a></li>
                        <li><a href="http://www.senate.mn/media/media_coming_up.php?ls=">Webcast Schedule</a></li>
                        <li><a href="http://www.senate.mn/media/index.php?ls=&type=audio">Audio Archives</a></li>
                        <li><a href="http://www.senate.mn/media/index.php?ls=&type=video">Video Archives</a></li>
                        <li><a href="http://www.senate.mn/media/media_photos.php">Photos</a></li>
                    </ul>
                    <ul>
                        <li><h3>Joint</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/htv/htv.asp">Broadcast TV Schedule</a></li>
                        <li><a href="http://www.lcc.leg.mn/meetings-all.htm">Commission Audio/Video</a></li>
                    </ul>
                </div>
            </li>

            <li class="leg_NavItem">
                <a class="leg_LegNavTop" href="http://www.leg.state.mn.us/leg/publicat.aspx" accesskey="p">Publications</a>
                <a class="leg_mobile_Accordion">&nbsp;</a>

                <div class="leg_LegNavCore" id="leg_nav_publications">    
                    <h2>Legislative Research, Reports &amp; Information</h2>
                    <ul>
                        <li><h3>Office Research &amp; Reports</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/fiscal/fahome.asp">House Fiscal Analysis</a></li> 
                        <li><a href="http://www.house.leg.state.mn.us/hrd/publications.aspx">House Research</a></li> 
                        <li><a href="http://www.auditor.leg.state.mn.us/ped/pedintro.htm">Legislative Auditor</a></li>
                        <li><a href="https://www.revisor.mn.gov/office/publications.php">Revisor Publications</a></li>
                        <li><a href="http://www.senate.leg.state.mn.us/publications">Senate Publications</a></li>                                            
                        <li><a href="http://www.leg.state.mn.us/lrl/">Library</a></li>
                    </ul>
                    <ul>
                        <li><h3>News</h3></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/sdaily.asp">House Session Daily</a></li>  
                        <li><a href="http://www.senate.leg.state.mn.us/media/">Senate Media Services</a></li>
                    </ul>
                    <ul>
                        <li><h3>Legislative History</h3></li>
                        <li><a href="http://www.leg.state.mn.us/leg/leghist/histstep.aspx">Minnesota Legislative History Guide</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/cco/journals/journl.asp">House Journal</a></li>
                        <li><a href="http://www.senate.leg.state.mn.us/journals/index.php#current">Senate Journal</a></li>
                        <li><a href="http://www.leg.state.mn.us/lrl/timecapsule/index.aspx">Legislative Time Capsule</a></li> 
                        <li><a href="http://www.leg.state.mn.us/lrl/vetoes/vetoes.aspx">Vetoes</a></li>                        
                    </ul>
                    <ul>
                        <li><h3>Notable Documents</h3></li>
                        <li><a href="http://www.senate.leg.state.mn.us/departments/scr/report/index.php#budgetsummaries">Fiscal Review</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hrd/databook/datamain.aspx">MN Government in Brief</a></li>
                        <li><a href="http://www.leg.state.mn.us/lrl/issues/">Minnesota Issues Guides</a></li>
                        <li><a href="http://www.house.leg.state.mn.us/hinfo/newlaws/newlawsmain.asp">New Laws</a></li>                                            
                        <li><a href="http://www.leg.state.mn.us/lrl/booksreports.aspx">Books &amp; reports</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
    <!-- end: main legislative nav -->

    <!-- start: masthead title & banner -->
    <div class="leg_Masthead">
        <div class="leg_Banner">
            <a class="leg_MainTitle" href="http://www.gis.leg.mn/">Legislative Coordinating Commission</a>
            <a class="leg_SubTitle"  href="#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Geospatial Information</a>
        </div>  
    </div>
    <!-- end: masthead -->
    
    <!-- start: mobile-specific office nav heading -->
    <div class="leg_mobile_NavHeader" id="leg_mobile_OfficeNavHeader">
        <h2>LCC Geospatial Info Menu</h2>
    </div>
    <!-- end: mobile-specific office nav heading -->

    <!-- begin: office/dept specific contextual navigation -->
<div class="leg_OfficeNav" id="leg_OfficeNav" tabindex="0">
        <!-- start: optional social media links -->
        <!-- [*Add/modify social media links] -->        
	<a href="javascript:window.print();" class="leg_Print"></a>
        <!--<a class="leg_SocialYoutube" href="#"></a>        
        <a class="leg_SocialTwitter" href="#"></a>
        <a class="leg_SocialFB" href="#"></a> -->
        <a class="leg_SocialEmail" href="http://www.gis.leg.mn/html/staff.html"></a>
        <!-- end: optional social media -->

        <ul>
<!--<li class="leg_NavItem"><a class="leg_OfficeNavLinkonly" href="#">[*Office Nav Example]</a></li>-->

<!-- <li class="leg_NavItem"><a class="leg_OfficeNavLinkonly" href="#">[*Office Nav Example]</a></li> -->

<!--End Copy Section-->

<li class="leg_NavItem">
<a class="leg_OfficeNavLinkonly" href="http://www.gis.leg.mn/index.html">Home</a>
<!-- accordion class is for dropdowns in mobile display -->
</li>


<li class="leg_NavItem">
<h3><a class="leg_OfficeNavTop" href="http://www.gis.leg.mn/hsemapdata.htm">Maps and Data</a>
<a class="leg_mobile_Accordion">&nbsp;</a></h3>  <!-- accordion class is for dropdowns in mobile display -->
                
<div class="leg_OfficeNavCore">
<ul>
	<li><a href="http://www.gis.leg.mn/html/maps.html">Maps Page</a></li>
	<li><a href="http://www.gis.leg.mn/hsemapdata.htm">House - Maps and Data</a></li>
	<li><a href="http://www.gis.leg.mn/senmapdata.htm">Senate - Maps and Data</a></li>
	<li><a href="http://www.gis.leg.mn/cngmapdata.htm">Congress - Maps and Data</a></li>
</ul>
</div>
</li>

<li class="leg_NavItem">
<h3><a class="leg_OfficeNavTop" href="http://www.gis.leg.mn/html/download.html">Data Services</a></h3>
<a class="leg_mobile_Accordion">&nbsp;</a>  <!-- accordion class is for dropdowns in mobile display -->
                
<div class="leg_OfficeNavCore">
<ul>
	<li><a href="http://www.gis.leg.mn/php/house.php">House District Information</a></li>
	<li><a href="http://www.gis.leg.mn/php/senate.php">Senate District Information</a></li>
	<li><a href="http://www.gis.leg.mn/php/congress.php">Congress District Information</a></li>
	<li><a href="http://www.gis.leg.mn/html/download.html">Download Data</a></li>
</ul>
</div>
</li>

<li class="leg_NavItem">
<h3><a class="leg_OfficeNavTop" href="http://www.gis.leg.mn/html/maps.html">Map Services</a></h3>
<a class="leg_mobile_Accordion">&nbsp;</a>  <!-- accordion class is for dropdowns in mobile display -->
                
<div class="leg_OfficeNavCore">
<ul>
	<li><a href="http://www.gis.leg.mn/OpenLayers/districts/">Who Represents Me</a></li>
	<li><a href="http://www.gis.leg.mn/OpenLayers/schooldistricts/">School District Finder</a></li>
	<li><a href="http://www.gis.leg.mn/OpenLayers/precincts/">Precinct Finder</a></li>
	<li><a href="http://www.gis.leg.mn/html/maps.html">More...</a></li>
</ul>
</div>
</li>

<li class="leg_NavItem">
<h3><a class="leg_OfficeNavTop" href="http://www.gis.leg.mn/html/redistricting.html">Redistricting</a></h3>
<a class="leg_mobile_Accordion">&nbsp;</a>  <!-- accordion class is for dropdowns in mobile display -->
                
<div class="leg_OfficeNavCore">
<ul>
	<li><h4>Redistricting Plans</h4></li>
	<li><a href="http://www.gis.leg.mn/redist2010/plans.php?plname=L2012&pltype=court">2012 Legislative Districts</a></li>
	<li><a href="http://www.gis.leg.mn/redist2010/cong10.php?name=C2012&pltype=court">2012 Congressional Districts</a></li>
<li><a href="http://www.gis.leg.mn/html/mcplans2013.html">2013 Metropolitan Council</a></li>
	<!--<li><a href="http://www.gis.leg.mn/html/leg02.html">2002 Legislative Districts</a></li>
	<li><a href="http://www.gis.leg.mn/html/cong02.html">2002 Congressional Districts</a></li> -->
</ul>
<ul>
	<li><h4>Redistricting Pages</h4></li>
	<li><a href="http://www.gis.leg.mn/html/redistricting.html">2010 Redistricting</a></li>
	<li><a href="http://www.gis.leg.mn/html/redistricting2000.html">2000 Redistricting</a></li>
	<li><a href="http://www.gis.leg.mn/html/redistricting1990.html">1990 Redistricting</a></li>
</ul>
</div>
</li>   

<li class="leg_NavItem">
<h3><a class="leg_OfficeNavTop" href="#">Information</a></h3>
<a class="leg_mobile_Accordion">&nbsp;</a>  <!-- accordion class is for dropdowns in mobile display -->
                
<div class="leg_OfficeNavCore">
<ul>
	<li><a href="http://www.gis.leg.mn/html/about.html">About</a></li>
	<li><a href="http://www.lcc.leg.mn/staff.html">Contact Us</a></li>
<li><a href="http://www.lcc.leg.mn/">LCC Home Page</a></li>
</div>
</li>

</ul>        
</div>  
    <!-- end: office/dept specific contextual navigation -->

</div>
<!-- end: header section -->

<!-- start: page-specific content section -->
<div class="leg_PageContent" id="leg_PageContent" tabindex="0">  
